use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use validator::Validate;
use crate::models::organization::Organization;
use crate::models::organization_user_role::OrganizationUserRoleSummary;
use crate::models::role::RoleSummary;

/// Login payload shape.
///
/// Notes for future AI-driven refactors:
/// - Validation is handled by actix-web-validator on extraction, thanks to `Validate` derives.
/// - Password is included here because typical login requires it; however, at the moment we do not verify it.
#[derive(Debug, Deserialize, Validate)]
pub struct LoginUserSchema {
    /// Email address of the user attempting to log in.
    #[validate(length(min = 4, max = 250, message = "Email must be between 4 to 250"))]
    #[validate(email(code = "code_str", message = "Invalid email address"))]
    pub email: String,
    /// Plain text password provided by the user.
    /// Currently unused for verification, but kept for forward compatibility.
    #[validate(length(min = 6, message = "Password must be greater than 8 characters"))]
    pub password: String,
}


/// User registration payload shape.
///
/// Notes for future AI-driven refactors:
/// - Validation is handled by actix-web-validator on extraction via the `Validate` derive.
/// - All fields are required and have length/format validations.
/// - First name and last name must be between 1-100 characters.
/// - Email must be valid format and between 4-250 characters.
/// - Password must be at least 6 characters.
#[derive(Debug, Deserialize, Validate)]
pub struct CreateUserSchema {
    /// User's first name, must be between 1-100 characters
    #[validate(length(min = 1, max = 100, message = "First name must be between 1 to 100"))]
    pub first_name: String,
    /// User's last name, must be between 1-100 characters
    #[validate(length(min = 1, max = 100, message = "Last name must be between 1 to 100"))]
    pub last_name: String,
    /// Valid email address, must be between 4-250 characters
    #[validate(length(min = 4, max = 250, message = "Email must be between 4 to 250"))]
    #[validate(email(code = "code_str", message = "Invalid email address"))]
    pub email: String,
    /// Password in plain text, must be at least 6 characters
    #[validate(length(min = 6, message = "Password must be greater than 6 characters"))]
    pub password: Option<String>,
    pub phone: Option<String>,
    pub organization_ids: Option<Vec<Uuid>>,
    pub permission_ids: Option<Vec<Uuid>>,
    pub user_role_id: Option<Uuid>,
    #[serde(default)]
    pub is_internal: bool,
}

#[derive(Debug, Deserialize, Validate)]
pub struct UpdateUserSchema {
    #[validate(length(min = 1, max = 100, message = "First name must be between 1 to 100"))]
    pub first_name: String,
    #[validate(length(min = 1, max = 100, message = "Last name must be between 1 to 100"))]
    pub last_name: String,
    #[validate(length(min = 4, max = 250, message = "Email must be between 4 to 250"))]
    #[validate(email(code = "code_str", message = "Invalid email address"))]
    pub email: String,
    pub phone: Option<String>,
    pub date_of_birth: Option<NaiveDate>,
    pub organization_ids: Option<Vec<Uuid>>,
    pub permission_ids: Option<Vec<Uuid>>,
    pub user_role_id: Option<Uuid>,
}

/// User domain model reflecting the `users` table.
///
/// This struct is used for fetching rows via SQLx and serializing back to clients.
/// Sensitive fields like `password` are marked with `skip_serializing` to avoid leaking secrets.
///
/// Columns are aligned with the migration in `src/migrations/20251016175919_create_users_table.up.sql`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    /// Primary key (generated by Postgres uuid_generate_v4())
    pub id: Uuid,
    pub first_name: String,
    pub last_name: String,
    pub email: String,
    pub phone: Option<String>,
    pub date_of_birth: Option<NaiveDate>,
    /// Password hash. Never serialize this field in API responses.
    #[serde(skip_serializing)]
    pub password: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password_reset_token: Option<String>,
    pub is_superuser: bool,
    pub is_internal: bool,
    #[serde(skip_serializing)]
    pub verification_token: Option<Uuid>,
    pub last_logged_in_at: Option<DateTime<Utc>>,
    pub current_logged_in_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserWithOrganizations {
    #[serde(flatten)]
    pub user: User,
    pub organizations: Vec<Organization>,
    // Permission role (admin, super-admin) for the queried org context.
    pub role: Option<RoleSummary>,
    // Job title (contractor, broker, …) for the queried org context.
    pub user_role: Option<OrganizationUserRoleSummary>,
}